2808 - instruction error imports/exports
adaptlearning/adapt-contrib-instructionError pull request #2
Opened 2021-11-18 15:11 UTC by eleanor-heath

https://github.com/adaptlearning/adapt_framework/issues/2808

2021-11-18 16:03 UTC, lc-alexanderbenesch approved these changes
👍

2021-11-18 16:28 UTC, cahirodoherty-learningpool approved these changes
👀

2021-11-22 15:49 UTC, oliverfoster requested changes

2021-11-22 15:49 UTC, oliverfoster commented on js/adapt-contrib-instructionError.js
> +    if (!this.config || !this.config._isEnabled) return;
```suggestion
    if (!this.config?._isEnabled) return;
```

2021-11-29 13:55 UTC, oliverfoster approved these changes

2021-11-29 13:55 UTC, merged